export const INGREDIENT_CATALOG = [
    { id: 'chicken', name: 'Chicken Breast', category: 'protein', icon: 'fitness-outline' },
    { id: 'eggs', name: 'Eggs', category: 'protein', icon: 'egg-outline' },
    { id: 'tuna', name: 'Tuna', category: 'protein', icon: 'fish-outline' },
    { id: 'salmon', name: 'Salmon', category: 'protein', icon: 'fish-outline' },
    { id: 'beef', name: 'Lean Beef', category: 'protein', icon: 'restaurant-outline' },
    { id: 'turkey', name: 'Turkey', category: 'protein', icon: 'nutrition-outline' },
    { id: 'tofu', name: 'Tofu', category: 'protein', icon: 'leaf-outline' },
    { id: 'beans', name: 'Beans', category: 'protein', icon: 'restaurant-outline' },
    { id: 'pollock', name: 'Pollock', category: 'protein', icon: 'fish-outline' },
    { id: 'greek_yogurt', name: 'Greek Yogurt', category: 'dairy', icon: 'ice-cream-outline' },
    { id: 'milk', name: 'Milk', category: 'dairy', icon: 'cafe-outline' },
    { id: 'rice', name: 'Rice', category: 'carb', icon: 'fast-food-outline' },
    { id: 'oats', name: 'Oats', category: 'carb', icon: 'basket-outline' },
    { id: 'potato', name: 'Potato', category: 'carb', icon: 'ellipse-outline' },
    { id: 'sweet_potato', name: 'Sweet Potato', category: 'carb', icon: 'ellipse-outline' },
    { id: 'bread', name: 'Whole Wheat Bread', category: 'carb', icon: 'albums-outline' },
    { id: 'pasta', name: 'Pasta', category: 'carb', icon: 'restaurant-outline' },
    { id: 'quinoa', name: 'Quinoa', category: 'carb', icon: 'nutrition-outline' },
    { id: 'tortilla', name: 'Tortilla', category: 'carb', icon: 'albums-outline' },
    { id: 'tomato', name: 'Tomato', category: 'vegetable', icon: 'ellipse-outline' },
    { id: 'broccoli', name: 'Broccoli', category: 'vegetable', icon: 'leaf-outline' },
    { id: 'spinach', name: 'Spinach', category: 'vegetable', icon: 'leaf-outline' },
    { id: 'lettuce', name: 'Lettuce', category: 'vegetable', icon: 'leaf-outline' },
    { id: 'cucumber', name: 'Cucumber', category: 'vegetable', icon: 'leaf-outline' },
    { id: 'carrot', name: 'Carrot', category: 'vegetable', icon: 'nutrition-outline' },
    { id: 'onion', name: 'Onion', category: 'vegetable', icon: 'ellipse-outline' },
    { id: 'pepper', name: 'Bell Pepper', category: 'vegetable', icon: 'ellipse-outline' },
    { id: 'mushroom', name: 'Mushroom', category: 'vegetable', icon: 'flower-outline' },
    { id: 'avocado', name: 'Avocado', category: 'fat', icon: 'leaf-outline' },
    { id: 'olive_oil', name: 'Olive Oil', category: 'fat', icon: 'water-outline' },
    { id: 'peanut_butter', name: 'Peanut Butter', category: 'fat', icon: 'disc-outline' },
    { id: 'almonds', name: 'Almonds', category: 'fat', icon: 'ellipse-outline' },
    { id: 'walnuts', name: 'Walnuts', category: 'fat', icon: 'ellipse-outline' },
    { id: 'banana', name: 'Banana', category: 'fruit', icon: 'nutrition-outline' },
    { id: 'berries', name: 'Berries', category: 'fruit', icon: 'color-palette-outline' },
    { id: 'apple', name: 'Apple', category: 'fruit', icon: 'ellipse-outline' },
    { id: 'orange', name: 'Orange', category: 'fruit', icon: 'ellipse-outline' },
    { id: 'dates', name: 'Dates', category: 'fruit', icon: 'nutrition-outline' },
    { id: 'cheese', name: 'Cheese', category: 'dairy', icon: 'cube-outline' },
    { id: 'cottage_cheese', name: 'Cottage Cheese', category: 'dairy', icon: 'ice-cream-outline' },
    { id: 'hummus', name: 'Hummus', category: 'fat', icon: 'restaurant-outline' },
];

export const MEAL_DATASET = [
    {
        id: 'm_chicken_rice',
        name: 'Chicken Rice Power Bowl',
        type: 'Lunch',
        ingredients: ['chicken', 'rice', 'broccoli', 'olive_oil'],
        alternatives: { broccoli: ['spinach', 'tomato', 'lettuce'], rice: ['quinoa', 'potato'] },
        calories: 640,
        protein: 48,
        carbs: 66,
        fats: 18,
        goals: ['muscle_gain', 'maintain'],
        dietTags: ['high_protein'],
        allergens: [],
        prepMinutes: 25,
        expertScore: 0.94,
        image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=80',
    },
    {
        id: 'm_egg_oats',
        name: 'Egg and Oat Breakfast Stack',
        type: 'Breakfast',
        ingredients: ['eggs', 'oats', 'banana', 'milk'],
        alternatives: { milk: ['greek_yogurt'], banana: ['berries', 'apple'] },
        calories: 520,
        protein: 31,
        carbs: 58,
        fats: 18,
        goals: ['muscle_gain', 'maintain'],
        dietTags: ['high_protein'],
        allergens: ['eggs', 'dairy'],
        prepMinutes: 12,
        expertScore: 0.9,
        image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80',
    },
    {
        id: 'm_tuna_toast',
        name: 'Tuna Avocado Toast',
        type: 'Lunch',
        ingredients: ['tuna', 'bread', 'avocado', 'lettuce'],
        alternatives: { tuna: ['chicken', 'turkey'], lettuce: ['spinach'] },
        calories: 470,
        protein: 36,
        carbs: 38,
        fats: 19,
        goals: ['weight_loss', 'maintain'],
        dietTags: ['high_protein'],
        allergens: ['fish', 'gluten'],
        prepMinutes: 10,
        expertScore: 0.88,
        image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=900&q=80',
    },
    {
        id: 'm_salmon_potato',
        name: 'Salmon Potato Recovery Plate',
        type: 'Dinner',
        ingredients: ['salmon', 'potato', 'spinach', 'olive_oil'],
        alternatives: { salmon: ['tuna', 'chicken'], potato: ['rice', 'quinoa'] },
        calories: 610,
        protein: 42,
        carbs: 44,
        fats: 28,
        goals: ['maintain', 'muscle_gain'],
        dietTags: ['omega_3'],
        allergens: ['fish'],
        prepMinutes: 30,
        expertScore: 0.92,
        image: 'https://images.unsplash.com/photo-1467003909585-2f8a7270028d?auto=format&fit=crop&w=900&q=80',
    },
    {
        id: 'm_greek_yogurt_bowl',
        name: 'Greek Yogurt Protein Bowl',
        type: 'Snack',
        ingredients: ['greek_yogurt', 'berries', 'oats', 'peanut_butter'],
        alternatives: { berries: ['banana', 'apple'], peanut_butter: ['avocado'] },
        calories: 430,
        protein: 29,
        carbs: 46,
        fats: 15,
        goals: ['weight_loss', 'maintain', 'muscle_gain'],
        dietTags: ['high_protein'],
        allergens: ['dairy', 'peanuts'],
        prepMinutes: 5,
        expertScore: 0.91,
        image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=900&q=80',
    },
    {
        id: 'm_tofu_quinoa',
        name: 'Tofu Quinoa Green Bowl',
        type: 'Dinner',
        ingredients: ['tofu', 'quinoa', 'broccoli', 'olive_oil'],
        alternatives: { broccoli: ['spinach', 'lettuce'], quinoa: ['rice'] },
        calories: 560,
        protein: 30,
        carbs: 62,
        fats: 21,
        goals: ['weight_loss', 'maintain'],
        dietTags: ['vegetarian', 'vegan'],
        allergens: ['soy'],
        prepMinutes: 22,
        expertScore: 0.87,
        image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80',
    },
    {
        id: 'm_beef_pasta',
        name: 'Lean Beef Pasta Builder',
        type: 'Dinner',
        ingredients: ['beef', 'pasta', 'tomato', 'spinach'],
        alternatives: { beef: ['turkey', 'chicken'], pasta: ['rice', 'potato'] },
        calories: 720,
        protein: 45,
        carbs: 82,
        fats: 22,
        goals: ['muscle_gain', 'weight_gain'],
        dietTags: ['high_energy'],
        allergens: ['gluten'],
        prepMinutes: 28,
        expertScore: 0.84,
        image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=900&q=80',
    },
    {
        id: 'm_turkey_hummus',
        name: 'Turkey Hummus Wrap',
        type: 'Lunch',
        ingredients: ['turkey', 'bread', 'hummus', 'lettuce', 'tomato'],
        alternatives: { turkey: ['chicken', 'tofu'], bread: ['rice'] },
        calories: 510,
        protein: 38,
        carbs: 48,
        fats: 17,
        goals: ['weight_loss', 'maintain'],
        dietTags: ['high_protein'],
        allergens: ['gluten', 'sesame'],
        prepMinutes: 8,
        expertScore: 0.89,
        image: 'https://images.unsplash.com/photo-1528733918455-5a59687cedf0?auto=format&fit=crop&w=900&q=80',
    },
    {
        id: 'm_smoothie_gain',
        name: 'Mass Gain Smoothie',
        type: 'Snack',
        ingredients: ['milk', 'banana', 'oats', 'peanut_butter', 'greek_yogurt'],
        alternatives: { milk: ['greek_yogurt'], banana: ['berries'] },
        calories: 690,
        protein: 38,
        carbs: 80,
        fats: 25,
        goals: ['weight_gain', 'muscle_gain'],
        dietTags: ['high_energy'],
        allergens: ['dairy', 'peanuts'],
        prepMinutes: 6,
        expertScore: 0.86,
        image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=900&q=80',
    },
    {
        id: 'm_veggie_omelette',
        name: 'Vegetable Omelette Plate',
        type: 'Breakfast',
        ingredients: ['eggs', 'spinach', 'tomato', 'avocado'],
        alternatives: { spinach: ['lettuce', 'broccoli'], avocado: ['olive_oil'] },
        calories: 410,
        protein: 26,
        carbs: 18,
        fats: 27,
        goals: ['weight_loss', 'maintain'],
        dietTags: ['low_carb', 'vegetarian'],
        allergens: ['eggs'],
        prepMinutes: 10,
        expertScore: 0.9,
        image: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=900&q=80',
    },
    {
        id: 'm_chicken_salad',
        name: 'Chicken Avocado Salad',
        type: 'Dinner',
        ingredients: ['chicken', 'lettuce', 'tomato', 'avocado', 'olive_oil'],
        alternatives: { chicken: ['turkey', 'tofu'], lettuce: ['spinach'] },
        calories: 520,
        protein: 42,
        carbs: 20,
        fats: 30,
        goals: ['weight_loss', 'maintain'],
        dietTags: ['low_carb', 'high_protein'],
        allergens: [],
        prepMinutes: 14,
        expertScore: 0.93,
        image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=80',
    },
    {
        id: 'm_quinoa_breakfast',
        name: 'Apple Quinoa Breakfast Bowl',
        type: 'Breakfast',
        ingredients: ['quinoa', 'apple', 'milk', 'berries'],
        alternatives: { milk: ['greek_yogurt'], apple: ['banana'] },
        calories: 460,
        protein: 19,
        carbs: 76,
        fats: 10,
        goals: ['maintain', 'weight_gain'],
        dietTags: ['balanced'],
        allergens: ['dairy'],
        prepMinutes: 15,
        expertScore: 0.82,
        image: 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=900&q=80',
    },
];

export const VALIDATION_CASES = [
    {
        profile: { age: 22, gender: 'male', height: 178, weight: 76, activityLevel: 'moderate', goal: 'muscle_gain' },
        fridge: ['chicken', 'rice', 'broccoli', 'eggs', 'oats', 'banana'],
        preferences: { likedIngredients: ['chicken', 'rice'], dislikedIngredients: [], allergies: [] },
        expectedTopGoals: ['muscle_gain', 'maintain'],
    },
    {
        profile: { age: 21, gender: 'female', height: 164, weight: 68, activityLevel: 'light', goal: 'weight_loss' },
        fridge: ['eggs', 'spinach', 'tomato', 'avocado', 'greek_yogurt', 'berries'],
        preferences: { likedIngredients: ['eggs', 'spinach'], dislikedIngredients: ['tuna'], allergies: ['fish'] },
        expectedTopGoals: ['weight_loss', 'maintain'],
    },
    {
        profile: { age: 24, gender: 'male', height: 181, weight: 64, activityLevel: 'active', goal: 'weight_gain' },
        fridge: ['milk', 'banana', 'oats', 'peanut_butter', 'pasta', 'beef'],
        preferences: { likedIngredients: ['peanut_butter', 'beef'], dislikedIngredients: [], allergies: [] },
        expectedTopGoals: ['weight_gain', 'muscle_gain'],
    },
];
